          <?php require_once('header3.php');?>
          <div class="inner cover">
            <h1 style="color:white;" class="cover-heading">Listen to your Books</h1>
            <p class="lead">This <a href="https://developer.spotify.com/">Spotify playlist</a> was generated by comparing <a href="http://www.alchemyapi.com/">keywords</a> from <a href="http://books.google.com/">book descriptions</a> to <a href="https://developer.musixmatch.com/">song lyrics</a>.</p>
            <p class="lead">
            </p>
          </div>
          <?php require_once('footer.php');?>